const courses = [
  {
    _id: "1",
    name: "Hedva",
    image: "/images/hedva.jpg",
    description: "חפש מורים פרטיים לחדווא",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Algebra",
    image: "/images/algebra.jpg",
    description: "חפש מורים פרטיים לאלגברה",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Hedva",
    image: "/images/hedva.jpg",
    description: "חפש מורים פרטיים לחדווא",
    brand: "Cannon",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Hedva",
    image: "/images/hedva.jpg",
    description: "חפש מורים פרטיים לחדווא",
    brand: "Sony",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Hedva",
    image: "/images/hedva.jpg",
    description: "חפש מורים פרטיים לחדווא",
    brand: "Logitech",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Hedva",
    image: "/images/hedva.jpg",
    description: "חפש מורים פרטיים לחדווא",
    brand: "Amazon",
    category: "Electronics",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default courses;
